public enum  PropertyType
{
	NONE								= -1,
	PT_FightValue						= 0,
	PT_Combat							= 1,
	PT_Firecontrol						= 2,
	PT_Protection						= 3,
	PT_Performance						= 4,
	PT_Durable							= 5,
	PT_CloseinAttack					= 6,
	PT_CloseinDefense					= 7,
	PT_DistanceAttack					= 8,
	PT_DistanceDefense					= 9,
	PT_Crit								= 10,
	PT_AntiCrit							= 11,
	PT_Hit								= 12,
	PT_Dodge							= 13,
	PT_IncreasedDamage					= 14,
	PT_IncreasedDamagePercentage		= 15,
	PT_DamageReduction					= 16,
	PT_DamageReductionPercentage		= 17,
	PT_CritIncreasePercentage			= 18,
	PT_CritReducePercentage				= 19,
	PT_CritHurt							= 20,
	PT_CritHurtPercentage				= 21,
	PT_CritDamageReduction				= 22,
	PT_CritReductionPercentage			= 23,
	PT_HitIncreasePercentage			= 24,
	PT_HitReductionPercentage			= 25,
	PT_DodgeIncreasePercentage			= 26,
	PT_DodgeReductionPercentage			= 27,
	PT_IgnoringDefense					= 28,
	PT_IgnoringDefensePercentage		= 29,
	PT_Energy							= 30,
	PT_Attack                           = 31,
	PT_AttackPercent                    = 32,
	PT_Damage                           = 33,
	PT_DamagePercent                    = 34,
	PT_numberMAX                        = 35,
	PT_HP								= 50,
	PT_MP								= 51,
	PT_MAGIC_WEAPON_ENERGY              = 52,
	PT_SKILL_USE_MAX_TIMES				= 71,
	PT_Money							= 100,
	PT_EMoney							= 101,
	PT_BagSlot							= 102,
	PT_StroeSlot						= 103,
	PT_Exp								= 104,
	PT_HONOR							= 105,
	PT_LEVEL							= 106,
	PT_MAKEINDEX						= 107,
	PT_ENERGYPIECE						= 108,
	PT_CORESTARTSTONE					= 109,
	PT_STONE_BUYTIMES					= 110,
	PT_MAX_POWER_TIME					= 111,
	PT_GET_GIFT_ID						= 112,
	PT_YWC_PLAY_TIMES					= 113,
	PT_ONLINE_GIFT_ID					= 114,
	PT_YWC_BUY_TIMES					= 115,
	PT_NEXT_GIFT_TIME					= 116,
	PT_TOTAL_ATTEN_ID					= 117,
	PT_UNITL_ATTEN_ID					= 118,
	PT_LAST_ATTEN_TIME					= 119,
	PT_MAX_POWER_BUY_TIMES				= 120,
	PT_BUY_TOTAL_EMONEY					= 121,
	PT_LAST_VIP_GIFT_ID					= 122,
	PT_DBQB_PLAY_TIMES					= 123,
	PT_DBQB_BUY_TIMES					= 124,
	PT_GROW_ID							= 125,
	PT_XZSL_BUY_TIMES					= 126,
	PT_XZSL_PLAY_TIMES					= 127,
	PT_TRIAL_BUY_NUM                    = 128,
	PT_TOTAL_TOTAL_ATTENDANCE_NUM		= 129,
	PT_ATTR_VIGOR_EXTRA                 = 130,
	PT_WHITE_CHESTS_FREE_TIME           = 131,
	PT_TRIAL_REFRESH_NUM                = 132,
	PT_FINISH_TRIAL_NUM                 = 133,
	PT_UPDATE_TRIAL_ID                  = 134,
	PT_ACCEPT_TRIAL_NUM                 = 135,
	PT_JJC_BEST_RANK					= 137,
	PT_JJC_BUY_TIMES					= 138,
	PT_JJC_PLAY_TIMES					= 139,
	PT_JJC_PLAY_CD						= 140,
	PT_JJC_HONOR						= 141,
	PT_TRIAL_TOWER_CUR_FLOOR            = 142,
	PT_TRIAL_TOWER_MAX_FLOOR            = 143,
	PT_TRIAL_TOWER_RESET_NUM            = 144,
	PT_STORE_SERVER_REFRESH_TIME        = 145,
	PT_STORE_REFRESH_TIMES              = 146,
	PT_STORE_BUY_ITEM_NUMBER            = 147,
	PT_SKILL_POINT						= 148,
	PT_LIVENESS_POINT                   = 149,
	PT_LIVENESS_STATE                   = 150,
	PT_ENERGY_GIFT_STATE                = 151,
	PT_GOLD_TIMES                       = 152,
	PT_SHWF_PLAY_TIMES					= 153,
	PT_SHWF_BUY_TIMES					= 154,
	PT_M_ATTEN_ID                       = 155,
	PT_M_ATTEN_TIME                     = 156,
	PT_LOGIN_TOTAL_TIMES                = 157,
	PT_BATTLE_WEAPON_ID                 = 158,
	PT_IS_FIRST_CHARGE                  = 159,
	PT_SPEND_TOTAL_STATE 				= 161,
	PT_RECHARGE_TOTAL_STATE 			= 162,
	PT_ONE_SPEND 						= 163,
	PT_ONE_RECHARGE 					= 164,
	PT_TOTAL_SPEND 						= 165,
	PT_TOTAL_RECHARGE 					= 166,
	PT_BUY_DUP_ENTER				    = 167,
	PT_TITLE_NAME                       = 168,
	PT_SPEND_ONE_STATE                  = 169,
	PT_RECHARGE_ONE_STATE				= 170,
	PT_UNTIL_RECHARGE_STATE             = 171,
	PT_UNTIL_RECHARGE_ID                = 172,
	PT_FRIEND_GET_ENERGY                = 173,
	PT_TRIAL_TOWER_STATE				= 174,
	PT_TRIAL_TOWER_POINT				= 175,
	PT_FUND_BUYSTATE					= 177,
	PT_FUND_AWARDSTATE					= 178,
	PT_QMFL_AWARDSTATE					= 179,
	PT_RANK_FIGHT_AWARD_STATE           = 180,
	PT_RANK_LEVEL_AWARD_STATE           = 181,
	PT_SHARE_AWARD_STATE				= 182,
	PT_ACT_ENERGY_BLOCK_NUM				= 183,
	PT_ACT_ENERGY_BLOCK_AWARD_STATE     = 184,
	PT_ACT_FIGHT_AWARD_STATE			= 185,
	PT_ACT_NORNAL_DUP_NUM               = 186,
	PT_ACT_HARD_DUP_NUM                 = 187,
	PT_ACT_DUP_AWARD_STATE				= 188,
	PT_ACT_WHITE_CHESTS_NUM				= 189,
	PT_ACT_GLOD_CHESTS_NUM				= 190,
	PT_ACT_CHESTS_STATE                 = 191,
	PT_ACT_ENERGY_BLUE                  = 192,
	PT_ACT_ENERGY_PURPLE				= 195,
	PT_ACT_ENERGY_GLOD					= 194,
	PT_ACT_ENERGY_QUILITY_STATE			= 193,
}

/// <summary>
/// Property value.
/// </summary>
public class PropertyValue
{
	public PropertyType		Type
	{ get; set; }
	
	public int 				Value
	{ get; set; }
	
	/// <summary>
	/// Initializes a new instance of the <see cref="PropertyValue"/> class.
	/// </summary>
	public PropertyValue()
	{}
	
	/// <summary>
	/// Initializes a new instance of the <see cref="PropertyValue"/> class.
	/// </summary>
	/// <param name="type">Type.</param>
	/// <param name="v">V.</param>
	public PropertyValue(PropertyType type, int v)
	{
		Type = type; Value = v;
	}
}
