import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

module("3100", package.seeall)

--[[
-- create monster
--]]
local function create_monster(nID, vPosition, nSqlID)
	return lua_export.create_monster("ET_MONSTER", EntityType.ET_MONSTER, nID, 
				vPosition, Vector3.one * 0.5, Vector3.zero, 0, nSqlID)
end

-- scene loading finish, game engine will call this function
function OnSceneStart()	

	-- start ai server
	lua_export.start_ai_server()
	
	local vSource 	= Vector3(57, 5, 41)
	local vOut		= Vector3.zero
	
	for id=0, 5, 1 do
		local vOut = lua_export.get_random_position(vSource, 5)
		if vOut ~= Vector3.zero then
			create_monster(id * -1, vOut, 1000)
		end
	end
end

--[[
/// <summary>
/// Gets or sets the I.
/// </summary>
/// <value>The I.</value>
public int 			ID
{ get; set; }

/// <summary>
/// Gets or sets the handle.
/// </summary>
/// <value>The handle.</value>
public object		Handle
{ get; set; }

/// <summary>
/// Gets or sets a value indicating whether this <see cref="CmdEvent+SceneTriggerEventArgs"/> is enter.
/// </summary>
/// <value><c>true</c> if enter; otherwise, <c>false</c>.</value>
public bool			Enter
{ get; set; }

/// <summary>
/// Gets or sets the event I.
/// </summary>
/// <value>The event I.</value>
public int 			EventID
{ get; set; }

/// <summary>
/// Gets or sets the target.
/// </summary>
/// <value>The target.</value>
public Collider 	Who
{ get; set; }
--]]
function OnSceneTrigger(evt)
end


