import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

module("3204", package.seeall)

-- scene loading finish, game engine will call this function
function OnSceneStart()	

	-- start ai server
	lua_export.start_ai_server()
end

--[[
/// <summary>
/// Gets or sets the I.
/// </summary>
/// <value>The I.</value>
public int 			ID
{ get; set; }

/// <summary>
/// Gets or sets the handle.
/// </summary>
/// <value>The handle.</value>
public object		Handle
{ get; set; }

/// <summary>
/// Gets or sets a value indicating whether this <see cref="CmdEvent+SceneTriggerEventArgs"/> is enter.
/// </summary>
/// <value><c>true</c> if enter; otherwise, <c>false</c>.</value>
public bool			Enter
{ get; set; }

/// <summary>
/// Gets or sets the event I.
/// </summary>
/// <value>The event I.</value>
public int 			EventID
{ get; set; }

/// <summary>
/// Gets or sets the target.
/// </summary>
/// <value>The target.</value>
public Collider 	Who
{ get; set; }
--]]
function OnSceneTrigger(evt)
end


