import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

module("login", package.seeall)

-- scene loading finish
function OnSceneStart()

end

-- scene update
function OnSceneUpdate()
	
end

-- scene destroy
function OnSceneDestroy()
end

