import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

module("madshadow_assault_02", package.seeall)

-- scene loading finish
function OnSceneStart()	
	local sqlScene = lua_export.get_sql_scene()
end

-- scene update
function OnSceneUpdate()
	
end

-- scene destroy
function OnSceneDestroy()

end
